version: '3.9'
include:
  - ./student/docker-compose.yaml
  - ./classroom/docker-compose.yaml
  - ./course/docker-compose.yaml

services:
  service-discovery:
    container_name: service-discovery
    build:
      context: ./service-discovery
    restart: always
    environment:
      ZIPKIN_HOST: distributed-tracing
    ports:
      - "8100:8100"

  distributed-tracing:
    image: openzipkin/zipkin:3.4
    container_name: distributed-tracing
    environment:
      STORAGE_TYPE: mem
    ports:
      - "9411:9411"

  pgadmin:
    image: dpage/pgadmin4:8.11.0
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: microservices
    ports:
      - 8888:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
