version: '3.9'
services:
  classroom-db:
    image: postgres:13-alpine
    container_name: classroom-db
    restart: always
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGPORT: ${DB_PORT}
    expose:
      - "${DB_PORT}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    command: -p ${DB_PORT}

  classroom:
    container_name: classroom
    build:
      context: .
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://classroom-db:${DB_PORT}/${DB}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      EUREKA_HOST: service-discovery
      ZIPKIN_HOST: distributed-tracing
      EVENTS_QUEUE_HOST: events-queue
      EVENTS_QUEUE_PORT: 5672
      EVENTS_EXCHANGE: internal.exchange
      EVENTS_ROUTING_KEY: events.routing-key
      PORT: 9200
    ports:
      - "9200:9200"
    depends_on:
      - service-discovery
      - distributed-tracing
      - classroom-db
      - events-queue