version: "3.9"
services:
  events-db:
    image: postgres:13-alpine
    container_name: events-db
    restart: always
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGPORT: ${DB_PORT}
    expose:
      - "${DB_PORT}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    command: -p ${DB_PORT}

  events-queue:
    container_name: events-queue
    build:
      context: .
      dockerfile: Dockerfile-queue
    restart: always
    volumes:
      - ./data/queue/data:/var/lib/rabbitmq
      - ./data/queue/log:/var/log/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  events:
    container_name: events
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://events-db:${DB_PORT}/${DB}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      EUREKA_HOST: service-discovery
      ZIPKIN_HOST: distributed-tracing
      EVENTS_QUEUE_HOST: events-queue
      EVENTS_QUEUE_PORT: 5672
      EVENTS_QUEUE_NAME: events.queue
      PORT: 9300
    ports:
      - "9300:9300"
    depends_on:
      - service-discovery
      - distributed-tracing
      - events-db
      - events-queue