version: "3.9"
services:
  course-db:
    image: postgres:13-alpine
    container_name: course-db
    restart: always
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGPORT: ${DB_PORT}
    expose:
      - "${DB_PORT}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    command: -p ${DB_PORT}
  course:
    build:
      context: .
    container_name: course
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://course-db:${DB_PORT}/${DB}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      EUREKA_HOST: service-discovery
      ZIPKIN_HOST: distributed-tracing
      PORT: 9101
    ports:
      - "9101:9101"
    depends_on:
      - service-discovery
      - distributed-tracing
      - course-db